### ISSUE TITLE
Please read...

### ISSUE THREAD

**Issue by bonndan** [DanishShah/DocX-PatientRecord#1]
more about using frameworks and web security. I've seen your post on G+ and I don't want to discourage you, but there are already a lot of similar OS apps and this one (sorry) is an example how not to do it.

See here:
https://github.com/DanishShah/DocX-PatientRecord/blob/master/DocX/include/update_patient.php

then read this:
https://www.owasp.org/index.php/SQL_Injection

Plus: State of the art frameworks (Symfony, Laravel, Yii, whatever...) provide all tools you need for safe data handling out of the box.

Sorry again and please don't feel offended personally.

**Comment by da9ish** [comment]
I know that there are a lot of apps on iOS and Android but my uncle needed a desktop application so I made this and secondly I'm a newbie so don't know a lot about security.
Well thanks for letting me know about it I'll surely work on it. Thanks
